name: Generate Source Tarball

# Trigger whenever a release is created
on:
  release:
    types:
      - created
  push:
    tags:
      - "v*.*"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: archive
      id: archive
      run: |
        VERSION=${GITHUB_REF##*/}
        test -z "$VERSION" && VERSION=${{ github.event.release.tag_name }}
        VERSION=$(printf "%s\n" "$VERSION" | sed 's/^v//')
        PKGNAME="ppsspp-$VERSION"
        mkdir -p /tmp/$PKGNAME
        mv * /tmp/$PKGNAME
        mv /tmp/$PKGNAME .
        find $PKGNAME/ffmpeg -name '*.a' -delete || true
        find $PKGNAME/ffmpeg -name '*.lib' -delete || true
        find $PKGNAME/ext -name '*.dylib' -delete || true
        find $PKGNAME/ext -name '*.lib' -delete || true
        find $PKGNAME/ext -name '*.so.*' -delete || true
        find $PKGNAME/dx9sdk -name '*.lib' -delete || true
        find $PKGNAME/dx9sdk -name '*.dll' -delete || true
        rm -rf $PKGNAME/ext/rapidjson/thirdparty/gtest || true
        sed -i "s;unknown;${VERSION};" $PKGNAME/git-version.cmake || true
        TARBALL=$PKGNAME.tar.xz
        tar cJf $TARBALL $PKGNAME
        echo "tarball=$TARBALL" >> $GITHUB_OUTPUT

    - name: upload tarball
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ steps.archive.outputs.tarball }}
        token: ${{ secrets.GITHUB_TOKEN }}
